name: badam
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  # flutter_xlider: ^3.2.0
  carousel_slider: ^1.4.1
  # cloud_firestore:
  shimmer: ^1.1.0
  # flutter_cache_manager: ^1.1.3
  url_launcher: ^5.4.2
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  share: ^0.6.3+6
  cupertino_icons: ^0.1.2
  firebase_core:
  http:
  # flutter_wordpress: ^0.1.4
  # dio: ^3.0.9
  shared_preferences: ^0.4.3
  # sqflite: 
  path_provider: 
  flutter_masked_text: ^0.8.0
  # cloud_firestore: ^0.12.3
  page_transition: ^1.1.5
  flutter_html: ^0.11.1
  font_awesome_flutter: ^8.8.1
  # custom_radio_button: ^0.0.3
  searchable_dropdown: ^1.1.3
  image_picker: ^0.6.4
  json_annotation: ^2.0.0

  # foveraite package
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
 
  flutter_paginator: ^0.0.6
  mime: ^0.9.6+3
  flutter_spinkit: ^4.1.2+1
  validators: ^2.0.0+1
  image_cropper: ^1.2.1
  rflutter_alert: ^1.0.3
  location: ^3.0.0
  # flutter_pagination_helper: ^1.0.1+2
  loadmore: ^1.0.4
  # flutter_map: ^0.9.0
  # geolocator: 
  # extended_text_field: ^0.5.0
  progress_dialog: ^1.2.0
  google_sign_in: ^4.0.4
  # firebase_storage: ^3.0.3
  google_maps_flutter: ^0.5.25+3
  photo_view: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/img/logo.png
   - assets/img/logo-larg.png
   - assets/img/logo-med.png
   - assets/img/logo-small.png
   - assets/img/background1.jpg
   - assets/img/placehoder.png
   - assets/img/Vault.png
   - assets/img/mapMarker.png
  
   - assets/email.png
   - assets/error.png
   - assets/google_logo.png
   - assets/sucesso.png
   - assets/user_default_img_white.png
    # - assets/images/credit_cards.png
   - assets/logo_app.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: "Vazir"
      fonts:
        - asset: assets/fonts/Vazir.ttf
        - asset: assets/fonts/Vazir-Light.ttf
          weight: 200
        - asset: assets/fonts/Vazir-Thin.ttf
          weight: 300
        - asset: assets/fonts/Vazir-Medium.ttf
          weight: 500
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
